language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo pip install cpp-coveralls
script:
  - make verif
after_success:
  - cd verif/ && ./test && gcov aleph.c
  - cp verif/ && coveralls --verbose --dryrun